---
# DATABASE CONFIG
site_database_server:    127.0.0.1
site_database_username:  root
site_database_password:  my_password
site_database_schema:    my_database
  
# CORE CONFIG
default_language: en-us

#IMAGE SETTINGS
image_save_dir:              /files
image_display_path:          /images
image_max_size:              2097152    # 2 Megabytes
image_accept_files:          image/jpeg, image/jpg
image_default_jpeg_quality:  99    # 1-100
image_max_width:             500   # in pixels
image_max_height:            500   # in pixels
  
# ERROR HANDLING
display_errors:  true;


